/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  color: {
    canvas: {
      key: "{color.canvas}",
      $type: "color",
      $value: "var(--theme-color-canvas)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-canvas)",
        key: "{color.canvas}",
      },
      name: "ColorCanvas",
      attributes: {
        category: "color",
        type: "canvas",
      },
      path: ["color", "canvas"],
    },
    surface: {
      key: "{color.surface}",
      $type: "color",
      $value: "var(--theme-color-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-surface)",
        key: "{color.surface}",
      },
      name: "ColorSurface",
      attributes: {
        category: "color",
        type: "surface",
      },
      path: ["color", "surface"],
    },
    "surface-raised": {
      key: "{color.surface-raised}",
      $type: "color",
      $value: "var(--theme-color-surface-raised)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-surface-raised)",
        key: "{color.surface-raised}",
      },
      name: "ColorSurfaceRaised",
      attributes: {
        category: "color",
        type: "surface-raised",
      },
      path: ["color", "surface-raised"],
    },
    "surface-muted": {
      key: "{color.surface-muted}",
      $type: "color",
      $value: "var(--theme-color-surface-muted)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-surface-muted)",
        key: "{color.surface-muted}",
      },
      name: "ColorSurfaceMuted",
      attributes: {
        category: "color",
        type: "surface-muted",
      },
      path: ["color", "surface-muted"],
    },
    "surface-disabled": {
      key: "{color.surface-disabled}",
      $type: "color",
      $value: "var(--theme-color-surface-disabled)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-surface-disabled)",
        key: "{color.surface-disabled}",
      },
      name: "ColorSurfaceDisabled",
      attributes: {
        category: "color",
        type: "surface-disabled",
      },
      path: ["color", "surface-disabled"],
    },
    text: {
      key: "{color.text}",
      $type: "color",
      $value: "var(--theme-color-text)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-text)",
        key: "{color.text}",
      },
      name: "ColorText",
      attributes: {
        category: "color",
        type: "text",
      },
      path: ["color", "text"],
    },
    "text-muted": {
      key: "{color.text-muted}",
      $type: "color",
      $value: "var(--theme-color-text-muted)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-text-muted)",
        key: "{color.text-muted}",
      },
      name: "ColorTextMuted",
      attributes: {
        category: "color",
        type: "text-muted",
      },
      path: ["color", "text-muted"],
    },
    "text-inverse": {
      key: "{color.text-inverse}",
      $type: "color",
      $value: "var(--theme-color-text-inverse)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-text-inverse)",
        key: "{color.text-inverse}",
      },
      name: "ColorTextInverse",
      attributes: {
        category: "color",
        type: "text-inverse",
      },
      path: ["color", "text-inverse"],
    },
    border: {
      key: "{color.border}",
      $type: "color",
      $value: "var(--theme-color-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-border)",
        key: "{color.border}",
      },
      name: "ColorBorder",
      attributes: {
        category: "color",
        type: "border",
      },
      path: ["color", "border"],
    },
    "border-strong": {
      key: "{color.border-strong}",
      $type: "color",
      $value: "var(--theme-color-border-strong)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-border-strong)",
        key: "{color.border-strong}",
      },
      name: "ColorBorderStrong",
      attributes: {
        category: "color",
        type: "border-strong",
      },
      path: ["color", "border-strong"],
    },
    accent: {
      key: "{color.accent}",
      $type: "color",
      $value: "var(--theme-color-accent)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-accent)",
        key: "{color.accent}",
      },
      name: "ColorAccent",
      attributes: {
        category: "color",
        type: "accent",
      },
      path: ["color", "accent"],
    },
    "accent-hover": {
      key: "{color.accent-hover}",
      $type: "color",
      $value: "var(--theme-color-accent-hover)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-accent-hover)",
        key: "{color.accent-hover}",
      },
      name: "ColorAccentHover",
      attributes: {
        category: "color",
        type: "accent-hover",
      },
      path: ["color", "accent-hover"],
    },
    "accent-contrast": {
      key: "{color.accent-contrast}",
      $type: "color",
      $value: "var(--theme-color-accent-contrast)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-accent-contrast)",
        key: "{color.accent-contrast}",
      },
      name: "ColorAccentContrast",
      attributes: {
        category: "color",
        type: "accent-contrast",
      },
      path: ["color", "accent-contrast"],
    },
    "accent-shadow": {
      key: "{color.accent-shadow}",
      $type: "color",
      $value: "var(--theme-color-accent-shadow)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-accent-shadow)",
        key: "{color.accent-shadow}",
      },
      name: "ColorAccentShadow",
      attributes: {
        category: "color",
        type: "accent-shadow",
      },
      path: ["color", "accent-shadow"],
    },
    control: {
      key: "{color.control}",
      $type: "color",
      $value: "var(--theme-color-control)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-control)",
        key: "{color.control}",
      },
      name: "ColorControl",
      attributes: {
        category: "color",
        type: "control",
      },
      path: ["color", "control"],
    },
    "control-hover": {
      key: "{color.control-hover}",
      $type: "color",
      $value: "var(--theme-color-control-hover)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-control-hover)",
        key: "{color.control-hover}",
      },
      name: "ColorControlHover",
      attributes: {
        category: "color",
        type: "control-hover",
      },
      path: ["color", "control-hover"],
    },
    "control-text": {
      key: "{color.control-text}",
      $type: "color",
      $value: "var(--theme-color-control-text)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-control-text)",
        key: "{color.control-text}",
      },
      name: "ColorControlText",
      attributes: {
        category: "color",
        type: "control-text",
      },
      path: ["color", "control-text"],
    },
    "control-border": {
      key: "{color.control-border}",
      $type: "color",
      $value: "var(--theme-color-control-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-control-border)",
        key: "{color.control-border}",
      },
      name: "ColorControlBorder",
      attributes: {
        category: "color",
        type: "control-border",
      },
      path: ["color", "control-border"],
    },
    "control-shadow": {
      key: "{color.control-shadow}",
      $type: "color",
      $value: "var(--theme-color-control-shadow)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-control-shadow)",
        key: "{color.control-shadow}",
      },
      name: "ColorControlShadow",
      attributes: {
        category: "color",
        type: "control-shadow",
      },
      path: ["color", "control-shadow"],
    },
    action: {
      key: "{color.action}",
      $type: "color",
      $value: "var(--theme-color-action)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-action)",
        key: "{color.action}",
      },
      name: "ColorAction",
      attributes: {
        category: "color",
        type: "action",
      },
      path: ["color", "action"],
    },
    "action-hover": {
      key: "{color.action-hover}",
      $type: "color",
      $value: "var(--theme-color-action-hover)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-action-hover)",
        key: "{color.action-hover}",
      },
      name: "ColorActionHover",
      attributes: {
        category: "color",
        type: "action-hover",
      },
      path: ["color", "action-hover"],
    },
    "action-border": {
      key: "{color.action-border}",
      $type: "color",
      $value: "var(--theme-color-action-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-action-border)",
        key: "{color.action-border}",
      },
      name: "ColorActionBorder",
      attributes: {
        category: "color",
        type: "action-border",
      },
      path: ["color", "action-border"],
    },
    "action-contrast": {
      key: "{color.action-contrast}",
      $type: "color",
      $value: "var(--theme-color-action-contrast)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-action-contrast)",
        key: "{color.action-contrast}",
      },
      name: "ColorActionContrast",
      attributes: {
        category: "color",
        type: "action-contrast",
      },
      path: ["color", "action-contrast"],
    },
    overlay: {
      key: "{color.overlay}",
      $type: "color",
      $value: "var(--theme-color-overlay)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-overlay)",
        key: "{color.overlay}",
      },
      name: "ColorOverlay",
      attributes: {
        category: "color",
        type: "overlay",
      },
      path: ["color", "overlay"],
    },
    danger: {
      key: "{color.danger}",
      $type: "color",
      $value: "var(--theme-color-danger)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-danger)",
        key: "{color.danger}",
      },
      name: "ColorDanger",
      attributes: {
        category: "color",
        type: "danger",
      },
      path: ["color", "danger"],
    },
    "danger-surface": {
      key: "{color.danger-surface}",
      $type: "color",
      $value: "var(--theme-color-danger-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-danger-surface)",
        key: "{color.danger-surface}",
      },
      name: "ColorDangerSurface",
      attributes: {
        category: "color",
        type: "danger-surface",
      },
      path: ["color", "danger-surface"],
    },
    "danger-contrast": {
      key: "{color.danger-contrast}",
      $type: "color",
      $value: "var(--theme-color-danger-contrast)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-danger-contrast)",
        key: "{color.danger-contrast}",
      },
      name: "ColorDangerContrast",
      attributes: {
        category: "color",
        type: "danger-contrast",
      },
      path: ["color", "danger-contrast"],
    },
    selected: {
      key: "{color.selected}",
      $type: "color",
      $value: "var(--theme-color-selected)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-selected)",
        key: "{color.selected}",
      },
      name: "ColorSelected",
      attributes: {
        category: "color",
        type: "selected",
      },
      path: ["color", "selected"],
    },
    "selected-border": {
      key: "{color.selected-border}",
      $type: "color",
      $value: "var(--theme-color-selected-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-selected-border)",
        key: "{color.selected-border}",
      },
      name: "ColorSelectedBorder",
      attributes: {
        category: "color",
        type: "selected-border",
      },
      path: ["color", "selected-border"],
    },
    "selected-contrast": {
      key: "{color.selected-contrast}",
      $type: "color",
      $value: "var(--theme-color-selected-contrast)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-selected-contrast)",
        key: "{color.selected-contrast}",
      },
      name: "ColorSelectedContrast",
      attributes: {
        category: "color",
        type: "selected-contrast",
      },
      path: ["color", "selected-contrast"],
    },
    "focus-ring-surface": {
      key: "{color.focus-ring-surface}",
      $type: "color",
      $value: "var(--theme-color-focus-ring-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-focus-ring-surface)",
        key: "{color.focus-ring-surface}",
      },
      name: "ColorFocusRingSurface",
      attributes: {
        category: "color",
        type: "focus-ring-surface",
      },
      path: ["color", "focus-ring-surface"],
    },
    "focus-ring-accent": {
      key: "{color.focus-ring-accent}",
      $type: "color",
      $value: "var(--theme-color-focus-ring-accent)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-focus-ring-accent)",
        key: "{color.focus-ring-accent}",
      },
      name: "ColorFocusRingAccent",
      attributes: {
        category: "color",
        type: "focus-ring-accent",
      },
      path: ["color", "focus-ring-accent"],
    },
    "dice-surface": {
      key: "{color.dice-surface}",
      $type: "color",
      $value: "var(--theme-color-dice-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-surface)",
        key: "{color.dice-surface}",
      },
      name: "ColorDiceSurface",
      attributes: {
        category: "color",
        type: "dice-surface",
      },
      path: ["color", "dice-surface"],
    },
    "dice-border": {
      key: "{color.dice-border}",
      $type: "color",
      $value: "var(--theme-color-dice-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-border)",
        key: "{color.dice-border}",
      },
      name: "ColorDiceBorder",
      attributes: {
        category: "color",
        type: "dice-border",
      },
      path: ["color", "dice-border"],
    },
    "dice-pip": {
      key: "{color.dice-pip}",
      $type: "color",
      $value: "var(--theme-color-dice-pip)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-pip)",
        key: "{color.dice-pip}",
      },
      name: "ColorDicePip",
      attributes: {
        category: "color",
        type: "dice-pip",
      },
      path: ["color", "dice-pip"],
    },
    "dice-disabled-surface": {
      key: "{color.dice-disabled-surface}",
      $type: "color",
      $value: "var(--theme-color-dice-disabled-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-disabled-surface)",
        key: "{color.dice-disabled-surface}",
      },
      name: "ColorDiceDisabledSurface",
      attributes: {
        category: "color",
        type: "dice-disabled-surface",
      },
      path: ["color", "dice-disabled-surface"],
    },
    "dice-disabled-pip": {
      key: "{color.dice-disabled-pip}",
      $type: "color",
      $value: "var(--theme-color-dice-disabled-pip)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-disabled-pip)",
        key: "{color.dice-disabled-pip}",
      },
      name: "ColorDiceDisabledPip",
      attributes: {
        category: "color",
        type: "dice-disabled-pip",
      },
      path: ["color", "dice-disabled-pip"],
    },
    "dice-active-ring": {
      key: "{color.dice-active-ring}",
      $type: "color",
      $value: "var(--theme-color-dice-active-ring)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-dice-active-ring)",
        key: "{color.dice-active-ring}",
      },
      name: "ColorDiceActiveRing",
      attributes: {
        category: "color",
        type: "dice-active-ring",
      },
      path: ["color", "dice-active-ring"],
    },
    "splash-spinner-idle": {
      key: "{color.splash-spinner-idle}",
      $type: "color",
      $value: "var(--theme-color-splash-spinner-idle)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-splash-spinner-idle)",
        key: "{color.splash-spinner-idle}",
      },
      name: "ColorSplashSpinnerIdle",
      attributes: {
        category: "color",
        type: "splash-spinner-idle",
      },
      path: ["color", "splash-spinner-idle"],
    },
    "splash-spinner-warning": {
      key: "{color.splash-spinner-warning}",
      $type: "color",
      $value: "var(--theme-color-splash-spinner-warning)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-splash-spinner-warning)",
        key: "{color.splash-spinner-warning}",
      },
      name: "ColorSplashSpinnerWarning",
      attributes: {
        category: "color",
        type: "splash-spinner-warning",
      },
      path: ["color", "splash-spinner-warning"],
    },
    "splash-spinner-success": {
      key: "{color.splash-spinner-success}",
      $type: "color",
      $value: "var(--theme-color-splash-spinner-success)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-splash-spinner-success)",
        key: "{color.splash-spinner-success}",
      },
      name: "ColorSplashSpinnerSuccess",
      attributes: {
        category: "color",
        type: "splash-spinner-success",
      },
      path: ["color", "splash-spinner-success"],
    },
    "splash-spinner-track": {
      key: "{color.splash-spinner-track}",
      $type: "color",
      $value: "var(--theme-color-splash-spinner-track)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-splash-spinner-track)",
        key: "{color.splash-spinner-track}",
      },
      name: "ColorSplashSpinnerTrack",
      attributes: {
        category: "color",
        type: "splash-spinner-track",
      },
      path: ["color", "splash-spinner-track"],
    },
    "glass-surface": {
      key: "{color.glass-surface}",
      $type: "color",
      $value: "var(--theme-color-glass-surface)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-glass-surface)",
        key: "{color.glass-surface}",
      },
      name: "ColorGlassSurface",
      attributes: {
        category: "color",
        type: "glass-surface",
      },
      path: ["color", "glass-surface"],
    },
    "glass-border": {
      key: "{color.glass-border}",
      $type: "color",
      $value: "var(--theme-color-glass-border)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-glass-border)",
        key: "{color.glass-border}",
      },
      name: "ColorGlassBorder",
      attributes: {
        category: "color",
        type: "glass-border",
      },
      path: ["color", "glass-border"],
    },
    "gradient-border-start": {
      key: "{color.gradient-border-start}",
      $type: "color",
      $value: "var(--theme-color-gradient-border-start)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-gradient-border-start)",
        key: "{color.gradient-border-start}",
      },
      name: "ColorGradientBorderStart",
      attributes: {
        category: "color",
        type: "gradient-border-start",
      },
      path: ["color", "gradient-border-start"],
    },
    "gradient-border-end": {
      key: "{color.gradient-border-end}",
      $type: "color",
      $value: "var(--theme-color-gradient-border-end)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-gradient-border-end)",
        key: "{color.gradient-border-end}",
      },
      name: "ColorGradientBorderEnd",
      attributes: {
        category: "color",
        type: "gradient-border-end",
      },
      path: ["color", "gradient-border-end"],
    },
    "ambient-primary": {
      key: "{color.ambient-primary}",
      $type: "color",
      $value: "var(--theme-color-ambient-primary)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-ambient-primary)",
        key: "{color.ambient-primary}",
      },
      name: "ColorAmbientPrimary",
      attributes: {
        category: "color",
        type: "ambient-primary",
      },
      path: ["color", "ambient-primary"],
    },
    "ambient-secondary": {
      key: "{color.ambient-secondary}",
      $type: "color",
      $value: "var(--theme-color-ambient-secondary)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-ambient-secondary)",
        key: "{color.ambient-secondary}",
      },
      name: "ColorAmbientSecondary",
      attributes: {
        category: "color",
        type: "ambient-secondary",
      },
      path: ["color", "ambient-secondary"],
    },
    "ambient-tertiary": {
      key: "{color.ambient-tertiary}",
      $type: "color",
      $value: "var(--theme-color-ambient-tertiary)",
      filePath: "src/design-tokens/color.semantic.json",
      isSource: true,
      original: {
        $type: "color",
        $value: "var(--theme-color-ambient-tertiary)",
        key: "{color.ambient-tertiary}",
      },
      name: "ColorAmbientTertiary",
      attributes: {
        category: "color",
        type: "ambient-tertiary",
      },
      path: ["color", "ambient-tertiary"],
    },
    sun: {
      100: {
        key: "{color.sun.100}",
        $value: "#eeddfd",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#EEDDFD",
          $type: "color",
          key: "{color.sun.100}",
        },
        name: "ColorSun100",
        attributes: {
          category: "color",
          type: "sun",
          item: "100",
        },
        path: ["color", "sun", "100"],
      },
      200: {
        key: "{color.sun.200}",
        $value: "#dcbbfc",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#DCBBFC",
          $type: "color",
          key: "{color.sun.200}",
        },
        name: "ColorSun200",
        attributes: {
          category: "color",
          type: "sun",
          item: "200",
        },
        path: ["color", "sun", "200"],
      },
      300: {
        key: "{color.sun.300}",
        $value: "#cb99fa",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#CB99FA",
          $type: "color",
          key: "{color.sun.300}",
        },
        name: "ColorSun300",
        attributes: {
          category: "color",
          type: "sun",
          item: "300",
        },
        path: ["color", "sun", "300"],
      },
      400: {
        key: "{color.sun.400}",
        $value: "#ba77f9",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#BA77F9",
          $type: "color",
          key: "{color.sun.400}",
        },
        name: "ColorSun400",
        attributes: {
          category: "color",
          type: "sun",
          item: "400",
        },
        path: ["color", "sun", "400"],
      },
      500: {
        key: "{color.sun.500}",
        $value: "#a855f7",
        $description: "Base colour",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#A855F7",
          $description: "Base colour",
          $type: "color",
          key: "{color.sun.500}",
        },
        name: "ColorSun500",
        attributes: {
          category: "color",
          type: "sun",
          item: "500",
        },
        path: ["color", "sun", "500"],
      },
      600: {
        key: "{color.sun.600}",
        $value: "#8815f4",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#8815F4",
          $type: "color",
          key: "{color.sun.600}",
        },
        name: "ColorSun600",
        attributes: {
          category: "color",
          type: "sun",
          item: "600",
        },
        path: ["color", "sun", "600"],
      },
      700: {
        key: "{color.sun.700}",
        $value: "#6609be",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#6609BE",
          $type: "color",
          key: "{color.sun.700}",
        },
        name: "ColorSun700",
        attributes: {
          category: "color",
          type: "sun",
          item: "700",
        },
        path: ["color", "sun", "700"],
      },
      800: {
        key: "{color.sun.800}",
        $value: "#44067f",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#44067F",
          $type: "color",
          key: "{color.sun.800}",
        },
        name: "ColorSun800",
        attributes: {
          category: "color",
          type: "sun",
          item: "800",
        },
        path: ["color", "sun", "800"],
      },
      900: {
        key: "{color.sun.900}",
        $value: "#22033f",
        filePath: "src/design-tokens/colors.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#22033F",
          $type: "color",
          key: "{color.sun.900}",
        },
        name: "ColorSun900",
        attributes: {
          category: "color",
          type: "sun",
          item: "900",
        },
        path: ["color", "sun", "900"],
      },
    },
  },
  font: {
    family: {
      1: {
        key: "{font.family.1}",
        $type: "fontFamily",
        $value: [
          "Outfit",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "fontFamily",
          $value: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          key: "{font.family.1}",
        },
        name: "FontFamily1",
        attributes: {
          category: "font",
          type: "family",
          item: "1",
        },
        path: ["font", "family", "1"],
      },
    },
    size: {
      1: {
        key: "{font.size.1}",
        $type: "dimension",
        $value: "14px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "14px",
          key: "{font.size.1}",
        },
        name: "FontSize1",
        attributes: {
          category: "font",
          type: "size",
          item: "1",
        },
        path: ["font", "size", "1"],
      },
      2: {
        key: "{font.size.2}",
        $type: "dimension",
        $value: "18px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "{font.size.base}",
          key: "{font.size.2}",
        },
        name: "FontSize2",
        attributes: {
          category: "font",
          type: "size",
          item: "2",
        },
        path: ["font", "size", "2"],
      },
      3: {
        key: "{font.size.3}",
        $type: "dimension",
        $value: "24px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "24px",
          key: "{font.size.3}",
        },
        name: "FontSize3",
        attributes: {
          category: "font",
          type: "size",
          item: "3",
        },
        path: ["font", "size", "3"],
      },
      4: {
        key: "{font.size.4}",
        $type: "dimension",
        $value: "32px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "32px",
          key: "{font.size.4}",
        },
        name: "FontSize4",
        attributes: {
          category: "font",
          type: "size",
          item: "4",
        },
        path: ["font", "size", "4"],
      },
      5: {
        key: "{font.size.5}",
        $type: "dimension",
        $value: "40px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "40px",
          key: "{font.size.5}",
        },
        name: "FontSize5",
        attributes: {
          category: "font",
          type: "size",
          item: "5",
        },
        path: ["font", "size", "5"],
      },
      6: {
        key: "{font.size.6}",
        $type: "dimension",
        $value: "110px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "110px",
          key: "{font.size.6}",
        },
        name: "FontSize6",
        attributes: {
          category: "font",
          type: "size",
          item: "6",
        },
        path: ["font", "size", "6"],
      },
      base: {
        key: "{font.size.base}",
        $type: "dimension",
        $value: "18px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "18px",
          key: "{font.size.base}",
        },
        name: "FontSizeBase",
        attributes: {
          category: "font",
          type: "size",
          item: "base",
        },
        path: ["font", "size", "base"],
      },
      clamp: {
        key: "{font.size.clamp}",
        $type: "dimension",
        $value: "clamp(3rem, -0.875rem + 8.333vw, 10rem)",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "clamp(3rem, -0.875rem + 8.333vw, 10rem)",
          key: "{font.size.clamp}",
        },
        name: "FontSizeClamp",
        attributes: {
          category: "font",
          type: "size",
          item: "clamp",
        },
        path: ["font", "size", "clamp"],
      },
    },
    "line-height": {
      1: {
        key: "{font.line-height.1}",
        $value: 1.5,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $value: 1.5,
          key: "{font.line-height.1}",
        },
        name: "FontLineHeight1",
        attributes: {
          category: "font",
          type: "line-height",
          item: "1",
        },
        path: ["font", "line-height", "1"],
      },
      2: {
        key: "{font.line-height.2}",
        $value: 1.75,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $value: 1.75,
          key: "{font.line-height.2}",
        },
        name: "FontLineHeight2",
        attributes: {
          category: "font",
          type: "line-height",
          item: "2",
        },
        path: ["font", "line-height", "2"],
      },
      3: {
        key: "{font.line-height.3}",
        $value: 1.25,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $value: 1.25,
          key: "{font.line-height.3}",
        },
        name: "FontLineHeight3",
        attributes: {
          category: "font",
          type: "line-height",
          item: "3",
        },
        path: ["font", "line-height", "3"],
      },
      4: {
        key: "{font.line-height.4}",
        $value: 1.1,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $value: 1.1,
          key: "{font.line-height.4}",
        },
        name: "FontLineHeight4",
        attributes: {
          category: "font",
          type: "line-height",
          item: "4",
        },
        path: ["font", "line-height", "4"],
      },
      5: {
        key: "{font.line-height.5}",
        $value: 0.925,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $value: 0.925,
          key: "{font.line-height.5}",
        },
        name: "FontLineHeight5",
        attributes: {
          category: "font",
          type: "line-height",
          item: "5",
        },
        path: ["font", "line-height", "5"],
      },
    },
    "letter-spacing": {
      1: {
        key: "{font.letter-spacing.1}",
        $type: "dimension",
        $value: "0",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "0",
          key: "{font.letter-spacing.1}",
        },
        name: "FontLetterSpacing1",
        attributes: {
          category: "font",
          type: "letter-spacing",
          item: "1",
        },
        path: ["font", "letter-spacing", "1"],
      },
      2: {
        key: "{font.letter-spacing.2}",
        $type: "dimension",
        $value: "1px",
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "dimension",
          $value: "1px",
          key: "{font.letter-spacing.2}",
        },
        name: "FontLetterSpacing2",
        attributes: {
          category: "font",
          type: "letter-spacing",
          item: "2",
        },
        path: ["font", "letter-spacing", "2"],
      },
    },
    weight: {
      1: {
        key: "{font.weight.1}",
        $type: "fontWeight",
        $value: 400,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "fontWeight",
          $value: 400,
          key: "{font.weight.1}",
        },
        name: "FontWeight1",
        attributes: {
          category: "font",
          type: "weight",
          item: "1",
        },
        path: ["font", "weight", "1"],
      },
      2: {
        key: "{font.weight.2}",
        $type: "fontWeight",
        $value: 700,
        filePath: "src/design-tokens/font.json",
        isSource: true,
        original: {
          $type: "fontWeight",
          $value: 700,
          key: "{font.weight.2}",
        },
        name: "FontWeight2",
        attributes: {
          category: "font",
          type: "weight",
          item: "2",
        },
        path: ["font", "weight", "2"],
      },
    },
    title: {
      1: {
        key: "{font.title.1}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 400,
          fontSize: "32px",
          lineHeight: 1.1,
        },
        $extensions: {
          $targetElement: "h1",
          $name: "Title 1",
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.1}",
            fontSize: "{font.size.4}",
            lineHeight: "{font.line-height.4}",
          },
          $extensions: {
            $targetElement: "h1",
            $name: "Title 1",
          },
          $type: "typography",
          key: "{font.title.1}",
        },
        name: "FontTitle1",
        attributes: {
          category: "font",
          type: "title",
          item: "1",
        },
        path: ["font", "title", "1"],
      },
      2: {
        key: "{font.title.2}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 400,
          fontSize: "24px",
          lineHeight: 1.1,
        },
        $extensions: {
          $targetElement: "h2",
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.1}",
            fontSize: "{font.size.3}",
            lineHeight: "{font.line-height.4}",
          },
          $extensions: {
            $targetElement: "h2",
          },
          $type: "typography",
          key: "{font.title.2}",
        },
        name: "FontTitle2",
        attributes: {
          category: "font",
          type: "title",
          item: "2",
        },
        path: ["font", "title", "2"],
      },
      3: {
        key: "{font.title.3}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 400,
          fontSize: "40px",
          lineHeight: 1.5,
        },
        $extensions: {
          $targetElement: "h3",
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.1}",
            fontSize: "{font.size.5}",
            lineHeight: "{font.line-height.1}",
          },
          $extensions: {
            $targetElement: "h3",
          },
          $type: "typography",
          key: "{font.title.3}",
        },
        name: "FontTitle3",
        attributes: {
          category: "font",
          type: "title",
          item: "3",
        },
        path: ["font", "title", "3"],
      },
      mega: {
        key: "{font.title.mega}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 400,
          fontSize: "clamp(3rem, -0.875rem + 8.333vw, 10rem)",
          lineHeight: 0.925,
        },
        $extensions: {
          $targetElement: "h1",
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.1}",
            fontSize: "{font.size.clamp}",
            lineHeight: "{font.line-height.5}",
          },
          $extensions: {
            $targetElement: "h1",
          },
          $type: "typography",
          key: "{font.title.mega}",
        },
        name: "FontTitleMega",
        attributes: {
          category: "font",
          type: "title",
          item: "mega",
        },
        path: ["font", "title", "mega"],
      },
    },
    body: {
      1: {
        key: "{font.body.1}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 400,
          fontSize: "18px",
          lineHeight: 1.5,
        },
        $extensions: {
          $targetElement: "p",
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.1}",
            fontSize: "{font.size.2}",
            lineHeight: "{font.line-height.1}",
          },
          $extensions: {
            $targetElement: "p",
          },
          $type: "typography",
          key: "{font.body.1}",
        },
        name: "FontBody1",
        attributes: {
          category: "font",
          type: "body",
          item: "1",
        },
        path: ["font", "body", "1"],
      },
    },
    button: {
      1: {
        key: "{font.button.1}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 700,
          fontSize: "18px",
          lineHeight: 1.5,
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.2}",
            fontSize: "{font.size.2}",
            lineHeight: "{font.line-height.1}",
          },
          $type: "typography",
          key: "{font.button.1}",
        },
        name: "FontButton1",
        attributes: {
          category: "font",
          type: "button",
          item: "1",
        },
        path: ["font", "button", "1"],
      },
      2: {
        key: "{font.button.2}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 700,
          fontSize: "24px",
          lineHeight: 1.5,
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.2}",
            fontSize: "{font.size.3}",
            lineHeight: "{font.line-height.1}",
          },
          $type: "typography",
          key: "{font.button.2}",
        },
        name: "FontButton2",
        attributes: {
          category: "font",
          type: "button",
          item: "2",
        },
        path: ["font", "button", "2"],
      },
      3: {
        key: "{font.button.3}",
        $value: {
          fontFamily: [
            "Outfit",
            "system-ui",
            "-apple-system",
            "Segoe UI",
            "Helvetica Neue",
            "Arial",
            "sans-serif",
          ],
          fontWeight: 700,
          fontSize: "32px",
          lineHeight: 1.5,
        },
        filePath: "src/design-tokens/font.json",
        isSource: true,
        $type: "typography",
        original: {
          $value: {
            fontFamily: "{font.family.1}",
            fontWeight: "{font.weight.2}",
            fontSize: "{font.size.4}",
            lineHeight: "{font.line-height.1}",
          },
          $type: "typography",
          key: "{font.button.3}",
        },
        name: "FontButton3",
        attributes: {
          category: "font",
          type: "button",
          item: "3",
        },
        path: ["font", "button", "3"],
      },
    },
  },
  spacing: {
    0: {
      key: "{spacing.0}",
      $value: "0px",
      $extensions: {
        semantic: "0",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "0px",
        $extensions: {
          semantic: "0",
        },
        $type: "dimension",
        key: "{spacing.0}",
      },
      name: "Spacing0",
      attributes: {
        category: "spacing",
        type: "0",
      },
      path: ["spacing", "0"],
    },
    1: {
      key: "{spacing.1}",
      $value: "4px",
      $extensions: {
        semantic: "2xs",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "4px",
        $extensions: {
          semantic: "2xs",
        },
        $type: "dimension",
        key: "{spacing.1}",
      },
      name: "Spacing1",
      attributes: {
        category: "spacing",
        type: "1",
      },
      path: ["spacing", "1"],
    },
    2: {
      key: "{spacing.2}",
      $value: "8px",
      $extensions: {
        semantic: "xs",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "8px",
        $extensions: {
          semantic: "xs",
        },
        $type: "dimension",
        key: "{spacing.2}",
      },
      name: "Spacing2",
      attributes: {
        category: "spacing",
        type: "2",
      },
      path: ["spacing", "2"],
    },
    3: {
      key: "{spacing.3}",
      $value: "12px",
      $extensions: {
        semantic: "sm",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "12px",
        $extensions: {
          semantic: "sm",
        },
        $type: "dimension",
        key: "{spacing.3}",
      },
      name: "Spacing3",
      attributes: {
        category: "spacing",
        type: "3",
      },
      path: ["spacing", "3"],
    },
    4: {
      key: "{spacing.4}",
      $value: "16px",
      $extensions: {
        semantic: "md",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "16px",
        $extensions: {
          semantic: "md",
        },
        $type: "dimension",
        key: "{spacing.4}",
      },
      name: "Spacing4",
      attributes: {
        category: "spacing",
        type: "4",
      },
      path: ["spacing", "4"],
    },
    5: {
      key: "{spacing.5}",
      $value: "24px",
      $extensions: {
        semantic: "lg",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "24px",
        $extensions: {
          semantic: "lg",
        },
        $type: "dimension",
        key: "{spacing.5}",
      },
      name: "Spacing5",
      attributes: {
        category: "spacing",
        type: "5",
      },
      path: ["spacing", "5"],
    },
    6: {
      key: "{spacing.6}",
      $value: "32px",
      $extensions: {
        semantic: "xl",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "32px",
        $extensions: {
          semantic: "xl",
        },
        $type: "dimension",
        key: "{spacing.6}",
      },
      name: "Spacing6",
      attributes: {
        category: "spacing",
        type: "6",
      },
      path: ["spacing", "6"],
    },
    7: {
      key: "{spacing.7}",
      $value: "56px",
      $extensions: {
        semantic: "2xl",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "56px",
        $extensions: {
          semantic: "2xl",
        },
        $type: "dimension",
        key: "{spacing.7}",
      },
      name: "Spacing7",
      attributes: {
        category: "spacing",
        type: "7",
      },
      path: ["spacing", "7"],
    },
    8: {
      key: "{spacing.8}",
      $value: "72px",
      $extensions: {
        semantic: "3xl",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "72px",
        $extensions: {
          semantic: "3xl",
        },
        $type: "dimension",
        key: "{spacing.8}",
      },
      name: "Spacing8",
      attributes: {
        category: "spacing",
        type: "8",
      },
      path: ["spacing", "8"],
    },
    9: {
      key: "{spacing.9}",
      $value: "96px",
      $extensions: {
        semantic: "4xl",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "96px",
        $extensions: {
          semantic: "4xl",
        },
        $type: "dimension",
        key: "{spacing.9}",
      },
      name: "Spacing9",
      attributes: {
        category: "spacing",
        type: "9",
      },
      path: ["spacing", "9"],
    },
    10: {
      key: "{spacing.10}",
      $value: "120px",
      $extensions: {
        semantic: "5xl",
      },
      filePath: "src/design-tokens/spacing.json",
      isSource: true,
      $type: "dimension",
      original: {
        $value: "120px",
        $extensions: {
          semantic: "5xl",
        },
        $type: "dimension",
        key: "{spacing.10}",
      },
      name: "Spacing10",
      attributes: {
        category: "spacing",
        type: "10",
      },
      path: ["spacing", "10"],
    },
  },
};
